-- 31/08/2026 — Fix critique : tirage_lot() ne verifiait jamais la quantite configuree
--
-- SIGNALE PAR ROMAIN : "il n'y aura pas un total de deux cent quatorze lots" -- en
-- sommant les lots reellement offerts par Marche Utile, Nook Cafe, Giordano, Auto-Ecole
-- de l'ARA, Carrosserie GP.
--
-- VERIFIE (requetes reelles, pas suppose) :
--   - Total configure (partenaires.lots ->quantite, somme sur tous les partenaires) : 59
--   - Total tirages en base (partenaire_id non nul)                                  : 214
--   - Total confirme+retire (notifie_at non nul)                                     : 59
--
-- Le total confirme+retire correspond EXACTEMENT au total configure -- un controle
-- humain manuel (Romain validant "Confirmer" un par un dans Stock des lots) a jusqu'ici
-- empeche tout depassement REEL envers les partenaires. Aucun partenaire n'a ete lese.
--
-- Mais 155 tirages (214-59) existent en base, JAMAIS confirmes, JAMAIS destines a
-- l'etre (le quota reel est deja atteint partout) -- des noms reels affiches comme
-- "a appeler" qui ne seront jamais appeles. Cause : tirage_lot(p_partenaire_id,
-- p_lot_nom, p_valeur, p_nb) inserait p_nb nouveaux tirages a chaque appel, sans
-- jamais verifier combien avaient deja ete tires pour ce meme lot. Rappele plusieurs
-- fois (tests, script re-execute, usage repete du bouton "Re-tirer") entre le 20/07
-- et le 03/08 -- tous les tirages en trop sont posterieurs a la cloture du festival
-- (18/07), le grand tirage de cloture ("Place de concert", hors partenaire) lui est
-- reste correctement borne aux dates du festival.
--
-- Detail par lot (ecart = tirages_reels - quantite_configuree) :
--   Utile Vence        Bon d'achat 10€           quantite 20  tires 60  ecart +40
--   Nook Cafe          Cafe gourmand              quantite 10  tires 43  ecart +33
--   Domaine Bergerie   Bon d'achat 20€           quantite  7  tires 29  ecart +22
--   Carrosserie GP     Bon d'achat 30€           quantite  6  tires 21  ecart +15
--   Nook Cafe          1 bagel offert             quantite  3  tires 17  ecart +14
--   Giordano           Bon d'achat 20€           quantite  5  tires 18  ecart +13
--   Auto-Ecole ARA     50€ remise permis auto     quantite  1  tires  9  ecart  +8
--   Nook Cafe          Formule complete           quantite  3  tires  8  ecart  +5
--   Auto-Ecole ARA     100€ remise BSR            quantite  2  tires  4  ecart  +2
--   Auto-Ecole ARA     100€ remise 125            quantite  2  tires  4  ecart  +2
--
-- CORRIGE (migration fix_tirage_lot_verifier_quantite) : tirage_lot() calcule desormais
-- le stock restant (quantite configuree - deja tires hors annule) et borne p_nb a ce
-- restant. Si le stock est deja epuise, retourne un ensemble vide (aucun insert), plus
-- de depassement silencieux possible. Verifie par appel reel (grant temporaire
-- supabase_read_only_user, revoque immediatement apres) : un appel sur un lot deja a
-- quota (Nook Cafe / Cafe gourmand, 43/10) retourne bien 0 ligne, aucun insert.
--
-- ============================================================================
-- ADDENDUM 31/08/2026 (meme jour, suite) -- NETTOYAGE EXECUTE
-- ============================================================================
-- Romain a confirme : "vire le tirage fantome... va dans la liste de gagnants et des
-- billets envoyes a chaque pro et email participants, tu retrouveras les vrais
-- gagnants" -- methode de verification qu'il a lui-meme indiquee : notifie_at est
-- precisement le marqueur pose quand le SA confirme un gagnant, etape qui declenche
-- l'envoi de l'email/billet. notifie_at IS NULL = jamais notifie = jamais d'email/
-- billet envoye.
--
-- CORRECTION IMPORTANTE PAR RAPPORT A L'ESTIMATION INITIALE CI-DESSUS : l'estimation
-- de "155 tirages fantomes, jamais confirmes ET jamais retires" etait imprecise.
-- Verification plus fine juste avant execution : sur les 155 lignes non-notifiees,
-- seules 2 etaient vraiment "jamais touchees" (ni notifie_at ni retire_at) -- les
-- 153 autres avaient retire_at RENSEIGNE (marquees "retirees") SANS jamais avoir ete
-- notifiees. Verifie avant de conclure : regroupees en seulement 3 rafales de
-- quelques heures chacune (28/07 15h-16h x47, 31/07 11h-16h x80, 03/08 12h-14h x26) --
-- profil de test/dev sans ambiguite, pas des festivaliers venant recuperer un lot
-- etale sur des jours/semaines. Coincide avec la periode de mise au point du circuit
-- de retrait (consulter_lot/valider_lot/verifier_pin_pro, cf. handoff du projet).
--
-- EXECUTE :
--   UPDATE tirages SET statut='annule'
--   WHERE partenaire_id IS NOT NULL AND notifie_at IS NULL AND statut <> 'annule';
--
-- RESULTAT VERIFIE APRES EXECUTION :
--   - 59 tirages actifs restants (partenaire_id non nul, statut<>'annule')
--   - 59 notifies (100% des restants) -- correspond EXACTEMENT au total configure
--   - 155 tirages annules (statut='annule', trace conservee, rien supprime)
--   - 21 tirages du grand tirage de cloture (partenaire_id null) totalement intouches
--
-- Aucun code applicatif modifie : partenaire_gagnants_etat() et partenaire_gagnants()
-- filtraient deja statut<>'annule' (verifie avant d'executer), /dashboard/nds-lots
-- reflete donc les chiffres corrects sans aucun changement de code -- seule la donnee
-- a change. Le bandeau d'alerte ajoute plus tot ce meme jour ne s'affiche plus
-- (totalFantome recalcule automatiquement a 0).

